### PR TITLE
seaglide prep

### PR DESCRIPTION
**Pull request by Ramiels**
Implemented seaglide wand, spell not functional (yet) and disabled spawning of wand (only enable for testing, remove line when finished)

### CODE REVIEW

**Comment by gustovafing** [comment]
gigachad

**Comment by SiriMoel** [comment]
me when work in progression

**Comment by SiriMoel** [comment]
sirmole

**Comment by Ramiels** [comment]
Sirmole (I just ate 12 inches of subway sandwich and are working on the spell)

**Comment by gustovafing** [comment]
sirmole

**Comment by Ramiels** [comment]
@ZacIsBurnt accept PR

**Review by gustovafing — APPROVED** [review]

**Pull request merged**
