### PR TITLE
Fixed fire extinguisher

### PR DESCRIPTION
**Pull request by Ramiels**
Spell previously had uniform spread and excessive recoil, nerfed recoil and set spell to create 6 wider projectiles in a random spread between 45 degrees (fixes lines from less spread and particle issues)

### CODE REVIEW

**Comment by Ramiels** [comment]
Also updated sprite and set it to convert liquid flames too

**Comment by gustovafing** [comment]
> Also updated sprite and set it to convert liquid flames too

nice

**Review by gustovafing — APPROVED** [review]

**Review by gustovafing — CHANGES_REQUESTED** [review]
Dont change the fire extinguisher sprite

**Comment by Ramiels** [comment]
fixes lag and visual improvements + performs better, and changes to fire extinguisher sprite was requested by @ZacIsBurnt

**Comment by gustovafing** [comment]
> changes to fire extinguisher sprite

He told me he didnt want the fire extinguisher sprite to be changed.

**Comment by Ramiels** [comment]
image current sprite is sideways so it needs to at least be flipped but otherwise I have my changes ready if @ZacIsBurnt does want it changed

**Comment by SiriMoel** [comment]
no i meant dont change the recoil
change the sprite but make sure it matches the subnautica concept art
idk where u got sprite from

**Comment by SiriMoel** [comment]
just dont touch the recoil >:(

**Review by SiriMoel — CHANGES_REQUESTED** [review]
dont touccc recoil :(

**Comment by Ramiels** [comment]
I just modelled it after a normal one I'll make it more subnautica-like but I'll fix the recoil

**Comment by gustovafing** [comment]
ok

**Comment by Ramiels** [comment]
this should be good

**Pull request merged**
